apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: circleguard-dev
  labels:
    app: file-service
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
        environment: dev
    spec:
      containers:
      - name: file-service
        image: juanamor8/circleguard-file-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: file-service-config
        - secretRef:
            name: circleguard-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
