apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
  namespace: circleguard-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: promotion-service
  template:
    metadata:
      labels:
        app: promotion-service
    spec:
      containers:
      - name: promotion-service
        image: juanamor8/circleguard-promotion-service:latest
        ports:
        - containerPort: 8088
        envFrom:
        - configMapRef:
            name: promotion-service-config
        - secretRef:
            name: circleguard-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8088
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
