version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: circleguard-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: circleguard
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - circleguard-net

  neo4j:
    image: neo4j:5.26
    container_name: circleguard-neo4j
    env_file:
      - .env
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-password}
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_connector_bolt_listen__address: :7687
      NEO4J_dbms_connector_bolt_advertised__address: :7687
    volumes:
      - neo4jdata:/data
    networks:
      - circleguard-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: circleguard-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - circleguard-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: circleguard-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - circleguard-net

  redis:
    image: redis:7.2
    container_name: circleguard-redis
    networks:
      - circleguard-net

  openldap:
    image: osixia/openldap:1.5.0
    container_name: circleguard-ldap
    env_file:
      - .env
    environment:
      LDAP_ORGANISATION: "CircleGuard"
      LDAP_DOMAIN: "circleguard.edu"
      LDAP_ADMIN_PASSWORD: ${LDAP_BIND_PASSWORD:-admin}
    networks:
      - circleguard-net

volumes:
  pgdata:
  neo4jdata:

networks:
  circleguard-net:
    driver: bridge
