apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: circleguard-master
type: Opaque
stringData:
  username: admin
  password: "${DB_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: circleguard-master
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "${DOCKER_CONFIG}"