FROM gradle:8.7-jdk21 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/services/circleguard-file-service
RUN gradle build -x test --no-daemon

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/services/circleguard-file-service/build/libs/*.jar app.jar

EXPOSE 8085
ENTRYPOINT ["java", "-jar", "app.jar"]
