FROM gradle:8.7-jdk21 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/services/circleguard-auth-service
RUN gradle build -x test --no-daemon

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/services/circleguard-auth-service/build/libs/*.jar app.jar
RUN cp services/circleguard-auth-service/src/main/resources/db/migration /app/db/migration 2>/dev/null || true

EXPOSE 8180
ENTRYPOINT ["java", "-jar", "app.jar"]