apiVersion: v1
kind: Secret
metadata:
  name: circleguard-secrets
  namespace: circleguard-stage
type: Opaque
stringData:
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  QR_SECRET: "${QR_SECRET}"
  LDAP_BIND_PASSWORD: "${LDAP_BIND_PASSWORD}"
  NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
  VAULT_SECRET: "${VAULT_SECRET}"
  VAULT_SALT: "${VAULT_SALT}"
  VAULT_HASH_SALT: "${VAULT_HASH_SALT}"
  TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
  TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
  TWILIO_FROM_NUMBER: "${TWILIO_FROM_NUMBER}"
  GOTIFY_TOKEN: "${GOTIFY_TOKEN}"
