apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
type: Opaque
stringData:
  slack_api_url: https://hooks.slack.com/services/placeholder
  smtp_auth_password: changeme
